# Schema for the configuration files of the node module.

external_entities.type.*:
  type: config_entity
  label: 'External entity type'
  mapping:
    label:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    read_only:
      type: boolean
      label: 'Read only'
    field_mappings:
      type: sequence
      label: 'Field mappings'
      sequence:
        type: sequence
        label: 'Field mapping'
        sequence:
          type: string
